version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies: github-actions"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - "dependencies: frontend"
    groups:
      tanstack:
        patterns:
          - "@tanstack/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "@testing-library/*"
      leaflet:
        patterns:
          - "leaflet"
          - "react-leaflet"
          - "@types/leaflet"
      module-federation:
        patterns:
          - "@module-federation/*"
      other-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "@tanstack/*"
          - "react"
          - "react-dom"
          - "@types/react*"
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"
          - "vite"
          - "@vitejs/*"
          - "vitest"
          - "@vitest/*"
          - "@testing-library/*"
          - "leaflet"
          - "react-leaflet"
          - "@types/leaflet"
          - "@module-federation/*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies: backend"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/backend/pkg/client"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies: backend"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/backend/pkg/plugin"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies: backend"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies: docker"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies: docker"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies: docker"

  - package-ecosystem: "docker"
    directory: "/.docker/migrations"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies: docker"
