apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- ../base/backend
- ../base/frontend
images:
- name: backend-image
  newName: ghcr.io/green-ecolution/green-ecolution/backend
  newTag: v0.1.0
- name: frontend-image
  newName: ghcr.io/green-ecolution/green-ecolution/frontend
  newTag: v0.1.0
- name: init-migrations-image
  newName: ghcr.io/green-ecolution/green-ecolution/migrations-postgres
  newTag: v0.1.0
generators:
- ./secret-generator.yaml
patches:
- path: config.yaml
- path: backend-deployment.yaml
