#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_MQTT_CLIENT_ID: ENC[AES256_GCM,data:KrCksUGWifATW4bB6EYQlA==,iv:YwGa7tl8F/p6rfyH64gB84mQlYU3MEPFOzLxLnX6cAE=,tag:CLyb3r+h39xtjj/8xfdkUQ==,type:str]
    GE_MQTT_USERNAME: ENC[AES256_GCM,data:0hQKQU0JWFGKbie+fEzuJleFwWd+hDCS,iv:UpYzDNWVpp1ENchTVtpt35R+vj5k91gjhkPo7cXJNXU=,tag:JZUAY6bpHBsLWpkWNgDhFw==,type:str]
    GE_MQTT_PASSWORD: ENC[AES256_GCM,data:cC4BlmCJyDBKweEagxuvmoHuyi8O5wnupOz3qOGPcUC8X/+Udzz8AcL5kVe6Yyqa+dPHRpfoQf8Px+8aeBeDMKhAiGGpyVCngnnoQAf9QAJbCPdlilDhPiwrSBFKzpCh/YUh/bN/sOFfpXFbrhj3WBu9a82GkMKWjbWABc+DL435eZxE,iv:HPfVYOR3/E2TNfzRK0EaFJ5fCKoV+zd/iUQBKWsRj/4=,tag:mu6diRW4jvELFbkQ2W0emA==,type:str]
    GE_SERVER_DATABASE_USERNAME: ENC[AES256_GCM,data:3iRZghtgypItyLzyS7dW7PedwqVUa/jnea/jwA==,iv:mOeL1RsuecAGqPGJl/W63+N4wuonW59LF/9mVkkWz+g=,tag:D8BQdymbS3ko3yUWa7PTng==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:zn/svwcOUpLosYY85ZqlfL6AZbIj740Nf341YsDpQ5BQTXieNmeE6JbpsTo=,iv:h0PJ5Ff/MqGpBQZy0jMASMRWNYmG7NCNzxntMmO+FgI=,tag:i+qqokaWWScaFtsADcg0Fw==,type:str]
    GE_S3_ROUTE_GPX_SECRETACCESSKEY: ENC[AES256_GCM,data:Xu4MMsT06ww4EAMYQjlILVAFsrbiCHNw2/MdAaVbpQGyIm0zcjctn2HJHBk=,iv:WnpHO8939DRG7OtPwB+j3W+5+43ljLo42TPHZ4t5rWM=,tag:CLJBKntJroSmcM+1jEgYQA==,type:str]
    #ENC[AES256_GCM,data:tYBkcaBmVWqMIQ==,iv:4H8sh86L/INYyesvdiz7++B24DS0zPkVtmpr/Xz7eyU=,tag:jsafePT2UiqR8x+XEYkNOw==,type:comment]
    GE_AUTH_OIDC_PROVIDER_BACKEND_CLIENT_SECRET: ENC[AES256_GCM,data:biKLiwNlZiQ1AGoE26j6hSDdXZyAAvIFddMz+5hlV6xwPumwqFD7YMeDyEw=,iv:0A0Ji+ZSKVvwKqpUbm4cmGzKUsufCOqWSbsT8WAgWRM=,tag:6ZZ3ffiAaQjwH2olTS8tOQ==,type:str]
    GE_AUTH_OIDC_PROVIDER_FRONTEND_CLIENT_SECRET: ENC[AES256_GCM,data:0yldurL2iVFOFQ4x8ZtL38N7Ziy7dBcwvPWp5uSBxQq7cTx1Qwqr5xVA8G8=,iv:V9MGnQcj6FROwwcVBfTT04dzo685+LQMl18MYQUf3TQ=,tag:X2SN80sTZUHXxVJtXiSzdg==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T13:33:16Z"
    mac: ENC[AES256_GCM,data:V3EJ3zznP9700zs2DRqMHbLHkZ5V4cLWlOxhD4ATiE1x6zT19QB+eMNcbOkNYkS4TWMDDD5x7y0uRucyADD3yEul4+Zt/wBFFn87O2X0JvxAXMirr0Rg3E4T8gO7zv2XDV4pxRdUC3caMatet/gU+K4aTSde15Vv1NBvRmmF8qM=,iv:voevXVBd6Ytzft4P9yMiCqojxEuocBgcfVi3ih1M9Lg=,tag:3hUfkh32AI+bJPKGGhn8sA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
