#ENC[AES256_GCM,data:CE0IV5i6nmUWj0UP3zaqdd37CwxCfF2VDFA4N8oH9cjXMmloOleSxVaYz/yGKORt8zzhdblnxYyvjQ==,iv:tLJk/59M1CeOz2Mo8HjD7Je/D++ulOABkbmwi0+WCwI=,tag:TwBNVbJs2I31aXyo91K7uw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_SERVER_DATABASE_USERNAME: ENC[AES256_GCM,data:iFE3eSlDtk/aW9LN3oy+e8tCYi6EfwHmbDjcHg==,iv:Md47PVobtTMOrxOgka5JlMHNcGdEznoWXUIrQnROQZo=,tag:5+sBhXnGd9gFah1mlgGFsg==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:Xe+2RzrTfrGFto+fQdVXKrVwh7xB6AVp9hAZVWGQST2tRiLX1YLjkIPre6YRYe4tajxuLtAFSr1BHSoJkjH+jw==,iv:vNIZskXtyPsQOV1tOn4Vw2mUudiTG0HP2Mjlvh1Hbh8=,tag:xIUEpE48teNaN8V0b47WPQ==,type:str]
    GE_S3_ROUTE-GPX_SECRETACCESSKEY: ENC[AES256_GCM,data:Z9vveJpY/E11QLR+z4LbDK5VEdikiWhA72UXM9MW6A0RviBmrT+raHtzaWI=,iv:b1upP43l+VwusOdGj38kG8y7AqRZMhwCKK2DogHJ28U=,tag:8zjZVbqtzwjK7n2OJdAmeQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMWF4QVJpQ0lpVUpxRmpL
            bm03TDJlOGIwM25kZnRLclhkb0piTWZWb0RBCmxNejdYTnRlaDVqdFVsai8zZllT
            MnhLV3BseFJCSmNDSjg1VmdQT0NRV00KLS0tIExmVjNwQnNBWTYxSGY5VkxJa1dO
            bTdyYllrNTNZTjl2QlVpc2N1eGNmc2cK9GxRJB+6tqKMpHFtBp8J/OHU5d2haFEg
            El1LAeEtbB28LRj6Ia3E4gv9hyj0LGzBaz0Rizi9AEtUZgQDjuWF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T16:21:45Z"
    mac: ENC[AES256_GCM,data:iFqopMYs06KmTQekfkjqfT+ZfB655bYwu+WSuY23xiekWO5f8GkYlBQoJ43EKxbUxS2jK6pa9MGIfJT+UwAFfD9sJ0wDKQcLupKLFDd4UH7QIZoLMmaSbObKvJH0/Gj6GeZbNt0uTaliPHcbip54p+ol8K6cOKwMe/sDm16xw8s=,iv:a4HFaGhcKMOLXfu585snZVM+r9FUGDiopNfDa5Yu3/A=,tag:raL2ypzC3WWiJBP7u/1WfQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
