#ENC[AES256_GCM,data:CE0IV5i6nmUWj0UP3zaqdd37CwxCfF2VDFA4N8oH9cjXMmloOleSxVaYz/yGKORt8zzhdblnxYyvjQ==,iv:tLJk/59M1CeOz2Mo8HjD7Je/D++ulOABkbmwi0+WCwI=,tag:TwBNVbJs2I31aXyo91K7uw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_SERVER_DATABASE_USERNAME: ENC[AES256_GCM,data:iFE3eSlDtk/aW9LN3oy+e8tCYi6EfwHmbDjcHg==,iv:Md47PVobtTMOrxOgka5JlMHNcGdEznoWXUIrQnROQZo=,tag:5+sBhXnGd9gFah1mlgGFsg==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:Xe+2RzrTfrGFto+fQdVXKrVwh7xB6AVp9hAZVWGQST2tRiLX1YLjkIPre6YRYe4tajxuLtAFSr1BHSoJkjH+jw==,iv:vNIZskXtyPsQOV1tOn4Vw2mUudiTG0HP2Mjlvh1Hbh8=,tag:xIUEpE48teNaN8V0b47WPQ==,type:str]
    GE_S3_ROUTE_GPX_SECRETACCESSKEY: ENC[AES256_GCM,data:puEAlVHdDnaQFmu6WBLig5DcN/E2mf4wB/uiD5OB7f0/insZq7qXozepkVA=,iv:EKKBwo54GU/3V6tR5yJeNazaiKwV2uTTJiv3c4eITHA=,tag:uv6d4xG0UljF2PFOWLWWCQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMWF4QVJpQ0lpVUpxRmpL
            bm03TDJlOGIwM25kZnRLclhkb0piTWZWb0RBCmxNejdYTnRlaDVqdFVsai8zZllT
            MnhLV3BseFJCSmNDSjg1VmdQT0NRV00KLS0tIExmVjNwQnNBWTYxSGY5VkxJa1dO
            bTdyYllrNTNZTjl2QlVpc2N1eGNmc2cK9GxRJB+6tqKMpHFtBp8J/OHU5d2haFEg
            El1LAeEtbB28LRj6Ia3E4gv9hyj0LGzBaz0Rizi9AEtUZgQDjuWF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T12:51:49Z"
    mac: ENC[AES256_GCM,data:i2BNg9xsnEC8wPyRSPBu2yha3sfoxQl7z9obdssIrkTUBd52gMqwyTha4NEn94fXBkWxrq5iCnPGwSj+2OIDPG9BschY+tvk89x8G89L+GPGE60bBMHLYwrz3EZu0xs+XI7ZP04t4J09XWF0Xbwg3goY5RmBJomhOg03njqBFx0=,iv:wSiobS27vyuCwv5BiraLMJG6TOvAmswvT1xhmRrKy4Y=,tag:w25IDTVrg9NJX1mq8NRZrw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
