#ENC[AES256_GCM,data:CE0IV5i6nmUWj0UP3zaqdd37CwxCfF2VDFA4N8oH9cjXMmloOleSxVaYz/yGKORt8zzhdblnxYyvjQ==,iv:tLJk/59M1CeOz2Mo8HjD7Je/D++ulOABkbmwi0+WCwI=,tag:TwBNVbJs2I31aXyo91K7uw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_SERVER_DATABASE_USER: ENC[AES256_GCM,data:PV1Wk9G7EOwA5ZbWeOSwrU+wM0ghlDVsJ1/+Bg==,iv:2XnoJrAPaQsXAkQn/loqp38s1CVgDuQiAb0YqmESuYs=,tag:dQoKU1m8twyvKhhTpBmKcw==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:Xe+2RzrTfrGFto+fQdVXKrVwh7xB6AVp9hAZVWGQST2tRiLX1YLjkIPre6YRYe4tajxuLtAFSr1BHSoJkjH+jw==,iv:vNIZskXtyPsQOV1tOn4Vw2mUudiTG0HP2Mjlvh1Hbh8=,tag:xIUEpE48teNaN8V0b47WPQ==,type:str]
    GE_S3_ROUTE-GPX_SECRETACCESSKEY: ENC[AES256_GCM,data:Z9vveJpY/E11QLR+z4LbDK5VEdikiWhA72UXM9MW6A0RviBmrT+raHtzaWI=,iv:b1upP43l+VwusOdGj38kG8y7AqRZMhwCKK2DogHJ28U=,tag:8zjZVbqtzwjK7n2OJdAmeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMWF4QVJpQ0lpVUpxRmpL
            bm03TDJlOGIwM25kZnRLclhkb0piTWZWb0RBCmxNejdYTnRlaDVqdFVsai8zZllT
            MnhLV3BseFJCSmNDSjg1VmdQT0NRV00KLS0tIExmVjNwQnNBWTYxSGY5VkxJa1dO
            bTdyYllrNTNZTjl2QlVpc2N1eGNmc2cK9GxRJB+6tqKMpHFtBp8J/OHU5d2haFEg
            El1LAeEtbB28LRj6Ia3E4gv9hyj0LGzBaz0Rizi9AEtUZgQDjuWF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T18:47:41Z"
    mac: ENC[AES256_GCM,data:FgcsI2Ta7J9TXzY1uS7WnNFg3UbSAtoF/l9E8Z8oMyAG2+E7oPI46X1YiF2Jz3VfUuldmPTR9BBlTbseeSEnBYP7iVL1tdTNEGKA7JDkpeLHB3ZM5PBbCQ2zgxs/gB1YLG4G3/oIlHYs79fWIoqHESecCEVwUEVk93wjdUudSM4=,iv:ATCrSiGtdWlcoVJ1N4vPDn9z1rhIQ4hSOQ7mQYri2NE=,tag:ejErIgbM1AMQ2HtopgGqJA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
