apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- ../base/backend
- ../base/frontend
images:
- name: backend-image
  newName: ghcr.io/green-ecolution/backend
  newTag: v1.2.0-9-g356d6e1a-stage
- name: frontend-image
  newName: ghcr.io/green-ecolution/frontend
  newTag: v1.2.0-3-g8b7f175-stage
- name: init-migrations-image
  newName: ghcr.io/green-ecolution/migrations-postgres
  newTag: v1.2.0-9-g356d6e1a-stage
generators:
- ./secret-generator.yaml
patches:
- path: config.yaml
- path: backend-deployment.yaml
