apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- ../base/backend
- ../base/frontend
images:
- name: backend-image
  newName: ghcr.io/green-ecolution/backend
  newTag: v1.3.0-nightly.20250909-2-g27b1648a-stage
- name: frontend-image
  newName: ghcr.io/green-ecolution/frontend
  newTag: v1.3.0-nightly.20250713-2-g976532f-stage
- name: init-migrations-image
  newName: ghcr.io/green-ecolution/migrations-postgres
  newTag: v1.3.0-nightly.20250909-2-g27b1648a-stage
generators:
- ./secret-generator.yaml
patches:
- path: config.yaml
- path: backend-deployment.yaml
