#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_MQTT_CLIENT_ID: ENC[AES256_GCM,data:oG9CZXYipI3XdXbVf4Meiw==,iv:qsQOZiLD4ZQUp9SZH5TvBoxi80d6s+iRLduYxv3cBtc=,tag:xlBs5ogxSmL8Ti+5gDPMOw==,type:str]
    GE_MQTT_USERNAME: ENC[AES256_GCM,data:AChQyLAPTr3JdI61nxHzQfSaUFOIQWp+,iv:9sFgkbOuQwXkDAAs6lJwkbT+T6GGXkLXtREZN0ECFbA=,tag:6m1n/Uho0PrqmK6Q6qiROg==,type:str]
    GE_MQTT_PASSWORD: ENC[AES256_GCM,data:9hsLKQ8N03Fqz8CwjjC1DcV61Si4186PrkxF8mvLrMMbISzbZQGYKz++1Gn8dhNheBAIvR3IS8VRz9bas4E9qNpsZ0K161ksdwTR4zpwViNB26ok9xxaghOAsb92uFbRQZnl0RGcvksE/a3YsucsjH/wN1xlr952soL8ueV0jsTFx1Nj,iv:xYkIMf1pIlREA9YrH+lvTMknJXn1erxOHT1Ye4BVDUs=,tag:rpGBHU0oGRL13lCCG7yfXA==,type:str]
    GE_SERVER_DATABASE_USERNAME: ENC[AES256_GCM,data:qAYplsxnEtS0K68LT1cVteMqVBhYD6Mf2zZ3Yw==,iv:I6zf5xIBrvrPGZ2zUqbALE9M06RUlGcohX7dOZLxBeI=,tag:UaDWyqhpXdJB1lBbBfJ2ZA==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:r+vLC3Iyv/Xunn632OaaiZwejZ2DrL16ltZ1t6U19mGLDwiv56YFpQ==,iv:cMPb7oMWPA7iLphbt09hkYg/i0olroJgz9kxOwNpxEA=,tag:LwYCRxcTIr5Q3sGID8rGyw==,type:str]
    GE_S3_ROUTE-GPX_SECRETACCESSKEY: ENC[AES256_GCM,data:s87XUHaBVIn6k6xOWEAcnWh6jGcMy9KsRSfb+paCaztzddgIMfKXKXHlWgA=,iv:L3Wo8ZXSKQxalS2QqUGHdSM0ZcNKx+JTJCGH1H8pSao=,tag:wkKYbrmEzT3VCJmd1jWcYQ==,type:str]
    GE_AUTH_OIDC_PROVIDER_BACKEND_CLIENT_SECRET: ENC[AES256_GCM,data:IZAlBndExPWpCFgJBvSOMOkWjRyUhxWsPebgOcBpYGnMmDKeJvjdfHS1sis=,iv:yREJTTkpMtePOh4GKld4IKLYeRW8kqwmyATBMrVvSTA=,tag:bFN5Gf/FERzNtn4xIw8+dw==,type:str]
    GE_AUTH_OIDC_PROVIDER_FRONTEND_CLIENT_SECRET: ENC[AES256_GCM,data:+5wTou/BRkhFmYaw5LivlKz5CuU5q48WTTaDQ7RHdBC12e+W7kyuU8hbJ3o=,iv:38ydxqxZrFwv7VxrupGegOhUN+BjAyfW6mHvnbAip08=,tag:jLgSGTYopknPl68aTei9IQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T13:54:10Z"
    mac: ENC[AES256_GCM,data:fkQ2X6h9WrmEO3mpmMtd+Rgrj821DgJ1wy9bcsLzcHuEw56hN8j0xbgO+UpbaFo83Ee6UP2JVI2FmaDvEe6xgDkCKTvptCQXxGC5N8DXOJqPBuLZJK9IAJbB0kuSN7+vDyJtsNHmhHWlaLI6B8htm8Wej1EzQPoC2gfyIM7sYuM=,iv:qSBfD6lxNc3sgFS6/6xPApYAKJ5jwmrC8UDajmN3bV4=,tag:nmp1mdSeuBuaYmLLuL+XJw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
