#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_MQTT_CLIENT_ID: ENC[AES256_GCM,data:oG9CZXYipI3XdXbVf4Meiw==,iv:qsQOZiLD4ZQUp9SZH5TvBoxi80d6s+iRLduYxv3cBtc=,tag:xlBs5ogxSmL8Ti+5gDPMOw==,type:str]
    GE_MQTT_USERNAME: ENC[AES256_GCM,data:AChQyLAPTr3JdI61nxHzQfSaUFOIQWp+,iv:9sFgkbOuQwXkDAAs6lJwkbT+T6GGXkLXtREZN0ECFbA=,tag:6m1n/Uho0PrqmK6Q6qiROg==,type:str]
    GE_MQTT_PASSWORD: ENC[AES256_GCM,data:9hsLKQ8N03Fqz8CwjjC1DcV61Si4186PrkxF8mvLrMMbISzbZQGYKz++1Gn8dhNheBAIvR3IS8VRz9bas4E9qNpsZ0K161ksdwTR4zpwViNB26ok9xxaghOAsb92uFbRQZnl0RGcvksE/a3YsucsjH/wN1xlr952soL8ueV0jsTFx1Nj,iv:xYkIMf1pIlREA9YrH+lvTMknJXn1erxOHT1Ye4BVDUs=,tag:rpGBHU0oGRL13lCCG7yfXA==,type:str]
    GE_SERVER_DATABASE_USERNAME: ENC[AES256_GCM,data:qAYplsxnEtS0K68LT1cVteMqVBhYD6Mf2zZ3Yw==,iv:I6zf5xIBrvrPGZ2zUqbALE9M06RUlGcohX7dOZLxBeI=,tag:UaDWyqhpXdJB1lBbBfJ2ZA==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:r+vLC3Iyv/Xunn632OaaiZwejZ2DrL16ltZ1t6U19mGLDwiv56YFpQ==,iv:cMPb7oMWPA7iLphbt09hkYg/i0olroJgz9kxOwNpxEA=,tag:LwYCRxcTIr5Q3sGID8rGyw==,type:str]
    GE_S3_ROUTE-GPX_SECRETACCESSKEY: ENC[AES256_GCM,data:s87XUHaBVIn6k6xOWEAcnWh6jGcMy9KsRSfb+paCaztzddgIMfKXKXHlWgA=,iv:L3Wo8ZXSKQxalS2QqUGHdSM0ZcNKx+JTJCGH1H8pSao=,tag:wkKYbrmEzT3VCJmd1jWcYQ==,type:str]
    GE_AUTH_OIDC_PROVIDER_BACKEND_CLIENT_SECRET: ENC[AES256_GCM,data:IZAlBndExPWpCFgJBvSOMOkWjRyUhxWsPebgOcBpYGnMmDKeJvjdfHS1sis=,iv:yREJTTkpMtePOh4GKld4IKLYeRW8kqwmyATBMrVvSTA=,tag:bFN5Gf/FERzNtn4xIw8+dw==,type:str]
    GE_AUTH_OIDC_PROVIDER_FRONTEND_CLIENT_SECRET: ENC[AES256_GCM,data:+5wTou/BRkhFmYaw5LivlKz5CuU5q48WTTaDQ7RHdBC12e+W7kyuU8hbJ3o=,iv:38ydxqxZrFwv7VxrupGegOhUN+BjAyfW6mHvnbAip08=,tag:jLgSGTYopknPl68aTei9IQ==,type:str]
    GE_AUTH_OIDC_PROVIDER_PUBLIC_KEY_STATIC: ENC[AES256_GCM,data:c9ObR/whw7qwsu1aXHUEttJjEkH9n98WzQyxd0KjhgI1BPQrWQFoeNoTMHq9ZRaPR1q/Zbzp4DaWIwivjfiCAQdz9Mg90l5mKHhyBdnufDEqtT70SMfhgIaX6rS/7BbONn2GDALeMV3tKxAaTXRD+WsaEvQ9aUQd+OBgP7mFgTWvU5BsXhXeOEaNIsuTNp6atzJMkE4A5qtmk4emi62zVVO62YW2FyL/0zfIPdhYPY1n2TduaC52duY7nzQsYknSut8LSk0SlGG6EtMHsFD4O//K0k4MV79lCQfJNdk2T4hj/S4FbNXFhRgOenBIS8BrNBK8gl9ft3fz7eQoYH5pdDVnvGaM4Yr0k/6OCi1e5I8dfwpmFtjesjC5uAGrGn0FsoTouxuAMEj4t2/P6rwcaFJaTss9k/lt0ezohJs+CwlBzTEZeGeotPYC+seg36FcF1yxRDPwj3OZXUKQQlGMK2tS8Hqtiqly2lXxHllbVvJCzw512eRAnOhAUvET/HyKpqyA4vJ5AMvsRNFio/wEuHIiPVW7XoNBpuCxKOcfD1UddPkPEeVB/kqrFLiwEXFAxfvA7TgMqTryZRbJ+fAh62jhw3cI86tRk2peh1vPUdYWSHVp5JfTjp42ftZF53xPGTmlSdSLaXTd6ICZLdSAXQeiPlW2MOz27REPfmE7TjZF+pzsoWU4BkJBDJM=,iv:nSLrIXLpPwMhEtliLL4gSKrSTJ6qvFaAG+Cj5Eswe90=,tag:F/sTscDlH7YkVwPncqd1aQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T22:14:04Z"
    mac: ENC[AES256_GCM,data:0rmn4Gn89g8pNllTkK0TtEoBP4amKqaaerXi9+EFerkutUrrqD/WKzXQL9BwEEn5z26qx6kE2rS+x01qOUWZ3cR7+Zvj/GrLjjZkdOtmiYg9ria6wfrrCj+yLfFi229whmzyTVVDRPFSoiiyNhqffIVTxJEUcIcWHx15a8Yz+rI=,iv:LRtvJ0F5CQSR/rJXIzhwyC+HRP2ZM0/ejP0oDW842IE=,tag:ja0YD0RSns5er2emXlGyDg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
