# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  GE_SERVER_APP_URL: "https://app.dev.green-ecolution.de"
  GE_SERVER_DEVELOPMENT: "true"

  GE_SERVER_DATABASE_HOST: "postgresql.postgres.svc.cluster.local"
  GE_SERVER_DATABASE_PORT: "5432"
  GE_SERVER_DATABASE_TIMEOUT: "30s"
  GE_SERVER_DATABASE_NAME: "green-ecolution-dev"

  GE_MQTT_BROKER: "eu1.cloud.thethings.industries:1883"
  GE_MQTT_TOPIC: "v3/sgr-students@zde/devices/tree-sensor/up"

  GE_AUTH_OIDC_PROVIDER_BASE_URL: "https://auth.green-ecolution.de"
  GE_AUTH_OIDC_PROVIDER_DOMAIN_NAME: "green-ecolution-dev"
  GE_AUTH_OIDC_PROVIDER_BACKEND_CLIENT_ID: "green-ecolution-backend"
  GE_AUTH_OIDC_PROVIDER_AUTH_URL: "https://auth.green-ecolution.de/realms/green-ecolution-dev/protocol/openid-connect/auth"
  GE_AUTH_OIDC_PROVIDER_TOKEN_URL: "https://auth.green-ecolution.de/realms/green-ecolution-dev/protocol/openid-connect/token"
  GE_AUTH_OIDC_PROVIDER_FRONTEND_CLIENT_ID: "green-ecolution-frontend"
  GE_ROUTING_START_POINT: "9.434764259345679,54.768731253913806"
  GE_ROUTING_END_POINT: "9.434764259345679,54.768731253913806"
  GE_ROUTING_WATERING_POINT: "9.434764259345679,54.768731253913806"
  GE_ROUTING_VALHALLA_HOST: "http://valhalla.routing.svc.cluster.local"
  GE_ROUTING_VALHALLA_OPTIMIZATION_VROOM_HOST: "http://vroom.routing.svc.cluster.local"
  GE_ROUTING_ORS_HOST: "http://ors.routing.svc.local"
  GE_ROUTING_ORS_OPTIMIZATION_VROOM_HOST: "http://vroom.routing.svc.cluster.local"
  GE_S3_ENDPOINT: "minio-hl.minio.svc.cluster.local:9000"
  GE_S3_REGION: "us-east-1"
  GE_S3_USE_SSL: "false"
  GE_S3_ROUTE-GPX_BUCKET: "routes-gpx"
  GE_S3_ROUTE-GPX_ACCESSKEY: "routes-gpx"

  TZ: "Europe/Berlin"
