#ENC[AES256_GCM,data:CE0IV5i6nmUWj0UP3zaqdd37CwxCfF2VDFA4N8oH9cjXMmloOleSxVaYz/yGKORt8zzhdblnxYyvjQ==,iv:tLJk/59M1CeOz2Mo8HjD7Je/D++ulOABkbmwi0+WCwI=,tag:TwBNVbJs2I31aXyo91K7uw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_MQTT_CLIENT_ID: ENC[AES256_GCM,data:odGpluJV9vjbZQm4907DjA==,iv:12CtFMjslxKsRWxW3XfWYpnIdNyFr3t5vFWGFyJukew=,tag:lzQGbv4IaPcgwKe09YCdyg==,type:str]
    GE_MQTT_USERNAME: ENC[AES256_GCM,data:BjxmbU1DVMsVYj8BJ20OONnhLKlSUg2O,iv:pLxXuc844KVyuH79dPwYQY5Lsix7RsKt8xSibsE4GZM=,tag:/589ohS6kQsFPtytJNBX6g==,type:str]
    GE_MQTT_PASSWORD: ENC[AES256_GCM,data:RPYgmdWpaQwca5BOVJQDjyxAjk70dBRN4ymX92pUq71zPQEnBCiM/cgP5vHj11wwecBle1vSOKUCja0BO6HEhKyS1BfaHwYsuZ+/9BG1f4PaOHDbcy3PtI0V7fFTQ8pX6MdJWS98qqw8/ZM/7pyA/PEJBl1nQMvZ6lhWfX/WbRH/UHim,iv:5TW1fTlfljDgm7tDFdaM5KyfTL2tiHPoEZlFSLp8Xo0=,tag:yy34t0ZNiddHkvJlO7sjrw==,type:str]
    GE_SERVER_DATABASE_USER: ENC[AES256_GCM,data:2LbitaVl5AjhHLFlOatWRSk2fecU89wxGsdaig==,iv:OceLdQBN5oxo/9+XoaetD6WMtvHPEGXjbh+Pa+A384c=,tag:x78Na1dOypSYzP+RUUXIqg==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:IW7IAP7t21VWUp2+JD+gTO0SOLXOlRc7NVmQ6pIsOFBLN1t+Rm+dL4wIhO8=,iv:K5QDdB9jEVZJyFdh1HYSRf0ljeyI2tiB/cnw7yivXOo=,tag:tkBvQ9FK9uZ2W1Y56fL1Ig==,type:str]
    GE_AUTH_OIDC_PROVIDER_BACKEND_CLIENT_SECRET: ENC[AES256_GCM,data:BMX8gvuMnTcX6/59iXHPjcbWHYVdOE+9QfT4nEHLxfwovOVi6uYG+XGiMOo=,iv:xI/wl614qwwyTtebRg0pDiTHTNIic2yB1QXavpLUXT4=,tag:05P6qT9knvj6H5h8H75LMw==,type:str]
    GE_AUTH_OIDC_PROVIDER_FRONTEND_CLIENT_SECRET: ENC[AES256_GCM,data:GgDoYpYkwSFPUjCFRlJaCK2tmVEZMQlkT0VWid2RcJrQA1jI7AXmZgNylT0=,iv:PstMdG01rXGUOdq2q9aL2L9/ym0NAX51ijBy2qjGPvc=,tag:MVZGjHRuTE3AXdx8Zod2nQ==,type:str]
    GE_S3_ROUTE-GPX_SECRETACCESSKEY: ENC[AES256_GCM,data:CN7KErLaE9KqPh5Gph/F/em773cbmFxU5sxvdcft4zIlIp8zk0dQ/rohLD8=,iv:B1euZ+J0paI8YZxSsokM3NNhjx5B8n8UZzrIu+duqq0=,tag:tgib+uUPyarLBq/TA++jqA==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMWF4QVJpQ0lpVUpxRmpL
            bm03TDJlOGIwM25kZnRLclhkb0piTWZWb0RBCmxNejdYTnRlaDVqdFVsai8zZllT
            MnhLV3BseFJCSmNDSjg1VmdQT0NRV00KLS0tIExmVjNwQnNBWTYxSGY5VkxJa1dO
            bTdyYllrNTNZTjl2QlVpc2N1eGNmc2cK9GxRJB+6tqKMpHFtBp8J/OHU5d2haFEg
            El1LAeEtbB28LRj6Ia3E4gv9hyj0LGzBaz0Rizi9AEtUZgQDjuWF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T13:54:39Z"
    mac: ENC[AES256_GCM,data:wYXt67xQ25/OjNc+0atUAx6kQ0CwBxQOLGitDbaT65WPcnqMTX5AVKdrDXPLaeUVtmlz8JhzhT7smP4YT4JZJykfOK2hHajqTlYyf6HNPQjBiwXnp2bjgsbFOYCDcx7nhvRIFCR/uXDx1z5b2XdhSV1el0k9XawSakZk1jYqSXU=,iv:uhpI/v34u6o1+vyeUE1udNauNcv513tnQjD1RSDpPGA=,tag:BhJ9gnuh7VaN3P32UKAyGQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
