name: "Frontend - Pull Request Checks"

on:
  pull_request:
    # paths:
    #   - "frontend/**"
    #   - ".github/workflows/frontend-pr.yaml"

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "./frontend/package.json"

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"

      - name: Install Dependencies
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ./frontend
        run: pnpm build

  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "./frontend/package.json"

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"

      - name: Install Dependencies
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile

      - name: Build backend-client and plugin-interface
        working-directory: ./frontend
        run: pnpm --filter=!frontend -r build

      - name: Linter
        continue-on-error: false
        working-directory: ./frontend
        run: pnpm lint

  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "./frontend/package.json"

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"

      - name: Install Dependencies
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile

      - name: Test
        working-directory: ./frontend
        run: pnpm test

  test_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test frontend Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: frontend:test
