name: "Test Dockerfile on PR"

on:
  pull_request:
    paths:
      - 'Dockerfile'
    branches:
      - develop

jobs:
  test_dockerfile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [stage, prod]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker file
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            ENV=${{ matrix.env }}
          file: Dockerfile
          platforms: linux/amd64
          push: false
          tags: |
            ghcr.io/${{ github.repository }}:test-pr-${{ matrix.env }}
            ghcr.io/${{ github.repository }}:test-pr-${{ matrix.env }}
